import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { App, ConfigProvider } from "antd";
import Providers from "@/components/providers";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: "#7b72e9",
                colorBgContainer: "#18181b",
                colorBgElevated: "#222228",
                colorBorder: "#2a2a30",
                colorText: "#eeeef0",
                colorTextPlaceholder: "#6b6b7a",
                borderRadius: 8,
              },
              components: {
                Form: {
                  labelColor: "#ffffff",
                },
                Input: {
                  activeBorderColor: "#7b72e9",
                  hoverBorderColor: "#5a52c4",
                },
                Button: {
                  primaryColor: "#ffffff",
                },
                Select: {
                  optionSelectedBg: "#7b72e9",
                  optionSelectedColor: "#ffffff",
                  optionActiveBg: "rgba(123, 114, 233, 0.15)",
                },
                Menu: {
                  darkItemBg: "var(--bg-card)",
                  darkItemSelectedBg: "var(--brand-tint)",
                  darkItemSelectedColor: "#7b72e9",
                  darkItemColor: "#9090a0",
                  darkItemHoverBg: "rgba(255,255,255,0.05)",
                  darkItemHoverColor: "#eeeef0",
                },
              },
            }}
          >
            <App>
              {children}
            </App>
          </ConfigProvider>
        </AntdRegistry>
        </Providers>
      </body>
    </html>
  );
}
