services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: notekeeper
      POSTGRES_PASSWORD: notekeeper
      POSTGRES_DB: notekeeper_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://notekeeper:notekeeper@db:5432/notekeeper_db?sslmode=disable
      JWT_SECRET: your_secret_here
    depends_on:
      - db

volumes:
  postgres_data:
